language: php

matrix:
  include:
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
    env: MEQP_CHECK=true CREATE_RELEASE=true
  - php: 7.3

sudo: false

cache:
  directories:
    - "$HOME/.cache/composer"
    - "$HOME/.composer/cache"

install:
  - travis_retry composer install --no-interaction

script:
  - sh travis.sh

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: Mollie_Payment.zip
  skip_cleanup: true
  on:
    tags: true
